### ISSUE TITLE
Translate Contato DT to Spanish

### ISSUE THREAD

**Issue by dman7** [socialappslab/denguetorpedo#205]
@brujonildo , James wants a translation of Contato DT as well. The following translations are needed:

```
notices:
  new:
    activity_title: "Título da atividade (máx 60 caracteres)"
    institution_name: "Instituição (máx 60 caracteres)"
    summary: "Descrição resumida (máx 150 caracteres)"
    description: "Descrição da atividade (máx 900 caracteres)"
    location: "Endereço da atividade (máx 60 caracteres)"
    date: "Data da atividade"
    time: "Hora da atividade"
```
